language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
matrix:
  allow_failures:
    - julia: 1.0
cache:
 directories:
   - /home/travis/.julia
addons:
  apt_packages:
    - gfortran
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- |
    if [[ "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then
      julia -e "Pkg.clone(pwd())"
      julia -e 'Pkg.test("Juniper", coverage=true)'
    else
      julia --project --color=yes -e "import Pkg; Pkg.instantiate(); Pkg.build();" #make sure the depedencies are working properly
      julia --check-bounds=yes --depwarn=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);";
    fi

after_success:
- |
    if [[ "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then
      julia -e  'Pkg.add("Coverage"); using Coverage; cd(Pkg.dir("Juniper")); LCOV.writefile("lcov.info", process_folder(".")); run(pipeline(`curl -s https://codecov.io/bash`, `bash`))'
    else
      julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Juniper")); using Coverage; Codecov.submit(process_folder())'
    fi
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
