language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
cache:
 directories:
   - /home/travis/.julia
addons:
  apt_packages:
    - gfortran
before_install:
- julia -e 'using Pkg; Pkg.update()'
script:
  julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("Juniper", coverage=true)'
after_success:
  julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Juniper")); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
